namespace Company.Videomatic.Application.Tests.Features.Videos;

[Collection("Sequence")]
public class ApplicationTests
{        
    [Theory]
    [InlineData(null, null, YouTubeVideos.HyonGakSunim_WhatIsZen)]
    public virtual async Task ImportVideoCommandWorks(
            [FromServices] ISender sender,
            [FromServices] IRepository<Video> repository,
            string videoId)
    {
        // Imports a video
        string url = YouTubeVideos.GetUrl(videoId);
        ImportVideoResponse response = await sender.Send(new ImportVideoCommand(url));

        // Verifies
        response.Should().NotBeNull();
        response.Video.Should().NotBeNull();
        response.Video.Id.Should().NotBe(0); // The id is generated by the storage
        response.Video.Thumbnails.Should().NotBeEmpty();
        response.Video.Transcripts.Should().NotBeEmpty();
        response.Video.Artifacts.Should().HaveCount(2);

        Video? video2 = await repository.FirstOrDefaultAsync(new GetVideoSpecification(response.Video.Id));
        video2.Should().NotBeNull();    
        response.Video.Should().BeEquivalentTo(video2);
        
        // Cleans up
        await repository.DeleteAsync(video2!);
    }

    [Theory]
    [InlineData(null, null)]
    public virtual async Task ImportVideoCommandWorksForAllVideos(
            [FromServices] ISender sender,
            [FromServices] IRepository<Video> repository)
    {
        var newIds = new HashSet<int>();        
        foreach (var videoId in YouTubeVideos.GetVideoIds())
        {            
            ImportVideoResponse response = await sender.Send(
                new ImportVideoCommand(YouTubeVideos.GetUrl(videoId)));

            newIds.Add(response.Video.Id).Should().BeTrue();                        
        }

        // Queries 
        IEnumerable<Video> videos = await repository.ListAsync(new GetVideosSpecification(newIds.ToArray()));
        videos.Should().HaveCount(newIds.Count);

        await repository.DeleteRangeAsync(videos);        
    }

    [Theory]
    [InlineData(null, null)]
    public virtual async Task DeleteVideoCommandWorksForAllVideos(
            [FromServices] ISender sender,
            [FromServices] IRepository<Video> repository)
    {        
        // Imports 4 videos
        var videoIds = YouTubeVideos.GetVideoIds();
        var newIds = new HashSet<int>();
        foreach (var videoId in videoIds)
        {
            ImportVideoResponse response = await sender.Send(
                new ImportVideoCommand(YouTubeVideos.GetUrl(videoId)));

            response.Video.Should().NotBeNull();
            newIds.Add(response.Video.Id);
        }

        // Queries 
        IEnumerable<Video> videos = await repository.ListAsync(new GetVideosSpecification(newIds.ToArray()));        
        videos.Should().HaveCount(newIds.Count);

        // Deletes
        foreach (var video in videos)
        {
            DeleteVideoResponse response = await sender.Send(new DeleteVideoCommand(video.Id));
            response.Deleted.Should().BeTrue(); 
        }        
    }
}
