using Company.Videomatic.Domain.Model;
using Company.Videomatic.Domain.Specifications;
using System.Runtime.CompilerServices;

namespace Company.Videomatic.Application.Tests.Features.Videos;

public class ApplicationTests
{
    [Theory]
    [InlineData(null, YouTubeVideos.HyonGakSunim_WhatIsZen)]
    public async Task ImportVideoUsingISender(
        [FromServices] ISender sender,
        string videoId)
    {
        var url = YouTubeVideos.GetUrl(videoId); // Something like http://www.youtube.com?v=32kjjkebewkjbew")
        ImportVideoResponse response = await sender.Send(new ImportVideoCommand(url));

        response.Should().NotBeNull();
        response.Video.Should().NotBeNull();
        response.Video.Id.Should().NotBe(0); // The id is generated by the storage
        response.Video.Thumbnails.Should().NotBeEmpty();
        response.Video.Transcripts.Should().NotBeEmpty();
        response.Video.Artifacts.Should().HaveCount(2);
    }

    [Theory]
    [InlineData(null, null, YouTubeVideos.HyonGakSunim_WhatIsZen)]
    public async Task ImportVideoUsingISender2(
            [FromServices] ISender sender,
            [FromServices] IVideoRepository repository,
            string videoId)
    {
        var url = YouTubeVideos.GetUrl(videoId);
        ImportVideoResponse response = await sender.Send(new ImportVideoCommand(url));
        
        response.Video.Id.Should().NotBe(0); // The id is generated by the storage

        // ...
        var video2 = await repository.GetVideoByIdAsync(new(response.Video.Id));
        response.Video.Should().BeEquivalentTo(video2);
    }

    [Theory]
    [InlineData(null, null)]
    public async Task ImportVideoUsingISender3(
            [FromServices] ISender sender,
            [FromServices] IVideoRepository repository)
    {
        var lastId = 0;
        var videoIds = YouTubeVideos.GetVideoIds(); 
        foreach (var videoId in videoIds)
        {
            var url = YouTubeVideos.GetUrl(videoId);
            ImportVideoResponse response = await sender.Send(new ImportVideoCommand(url));

            response.Video.Id.Should().NotBe(lastId); // The id is generated by the storage
            lastId = response.Video.Id;            
        }

        var spec = new GetVideosSpec();
        IEnumerable<Video> videos = await repository.GetVideosAsync(spec);

        videos.Should().NotBeNullOrEmpty();
        videos.Should().HaveCountGreaterThanOrEqualTo(videoIds.Length); 
        // ...        
    }
}
