namespace Company.Videomatic.Application.Tests.Features.Videos;

public class ApplicationTests
{
    [Theory]
    [InlineData(null, YouTubeVideos.HyonGakSunim_WhatIsZen)]
    public async Task ImportVideoUsingISender(
        [FromServices] ISender sender,
        string videoId)
    {
        var url = YouTubeVideos.GetUrl(videoId); // Something like http://www.youtube.com?v=32kjjkebewkjbew")
        ImportVideoResponse response = await sender.Send(new ImportVideoCommand(url));

        response.Should().NotBeNull();
        response.Video.Should().NotBeNull();
        response.Video.Id.Should().NotBe(0); // The id is generated by the storage
        response.Video.Thumbnails.Should().NotBeEmpty();
        response.Video.Transcripts.Should().NotBeEmpty();
        response.Video.Artifacts.Should().HaveCount(2);
    }

    [Theory]
    [InlineData(null, YouTubeVideos.HyonGakSunim_WhatIsZen)]
    public async Task ImportVideoUsingISender2(
            [FromServices] ISender sender,
            string videoId)
    {
        var url = YouTubeVideos.GetUrl(videoId); // Something like http://www.youtube.com?v=32kjjkebewkjbew")
        ImportVideoResponse response = await sender.Send(new ImportVideoCommand(url));

        // ...
    }

}
