global using Xunit;
global using Company.Videomatic.Application.Features.Playlists.Commands;
global using Company.Videomatic.Application.Features.Playlists.Queries;
global using Company.Videomatic.Application.Features.Videos.Commands;
global using Company.Videomatic.Application.Features.Videos.Queries;
global using FluentAssertions;
global using FluentValidation;
global using FluentValidation.TestHelper;
global using Microsoft.Extensions.DependencyInjection;
